TABLE_PORT = 10000
CONVERT_PORT = 9090
ENCONDING_FORMAT = "utf-8"
RECV_BUFFER_SIZE = 2048
IP_SERVER = '127.0.0.1'
HELO = 'HELO'
DATA = 'DATA'
QUIT = 'QUIT'
CONVERT = 'CONVERT'
TABLE = 'TABLE'
EM = 'EM'
EA = 'EA'
NMV = 'NMV'
NAV = "NAV"

